### PR TITLE
Update getAuthorizationStatus and requestNotificationPermissions to return the result of the respective calls

### LINKED ISSUE #64: Request: getAuthorizationStatus and requestNotificationPermissions should return futures
It would be nice to be able to wait for `getAuthorizationStatus` and/or `requestNotificationPermissions` to return. Those methods could wait to call `result` on the native side until the user takes action or the notification settings are returned, respectively. Something like changing this:
```
void getAuthorizationStatus() {
  _channel.invokeMethod('getAuthorizationStatus', []);
}
```

to something along the lines of this:

```
Future<String> getAuthorizationStatus() async {
  return  _channel.invokeMethod('getAuthorizationStatus', []);
}
```

### PR DESCRIPTION
**Pull request by fbcouch**
Resolves #64

### CODE REVIEW

**Comment by lordgreg** [comment]
Looks good to me. 

What do you think @szotp ?

**Comment by szotp** [comment]
Hi,
1. `final authorizationStatus = ValueNotifier<String?>(null);` should be removed because it's not getting changed anymore, and may mislead people who are already using this library.
2. `Future<String?>  getAuthorizationStatus()` seems unnecessary, because it will never return nil. Ideally we would return enum value, but non-nullable String also seems fine.

**Comment by fbcouch** [comment]
@szotp Those are good points – I removed the unused ValueNotifier and converted `getAuthorizationStatus` to return a new enum, `ApnsAuthorizationStatus`

**Review by szotp — APPROVED** [review]
Thanks, this looks good. 👍

**Comment by szotp** [comment]
@lordgreg please take over

**Comment by fbcouch** [comment]
@lordgreg Any additional changes needed here?

**Pull request merged**
